### ISSUE TITLE
displaying HAR

### ISSUE THREAD

**Issue by johndharrison** [hrbrmstr/splashr#1]
Hi Bob,

Thanks for adding this package I hadn't seen splash previously and it looks like a useful addition to the arsenal. I have a package HARtools which might be useful for displaying the HAR objects returned by splash. Might be of use https://github.com/johndharrison/HARtools

**Comment by hrbrmstr** [comment]
Aye! Yes! Doh! I had that in my original mental TODO and then totally forgot abt it once I got done extracting out the hacked code I made for a work thing that needed to use Splash and put it into an R package (that is often a pkg workflow these days :-) Def adding to the TODO and will add support for it. #ty for note, too. My noggin needs more and more prodding these days.

**Comment by hrbrmstr** [comment]
Current thinking is to:

- [X] Have `render_har()` just return a `HARtools::har` object
- [X] Have the HAR component of `render_json()` (if it was enabled in the call) be a `HARtools::har` object

**Comment by hrbrmstr** [comment]
That was easier than expected :-)

    splash("splash", 8050L) %>%
      render_har("http://www.poynter.org/") -> har

    print(har)
    ## --------HAR VERSION-------- 
    ## HAR specification version: 1.2 
    ## --------HAR CREATOR-------- 
    ## Created by: Splash 
    ## version: 2.3.1 
    ## --------HAR BROWSER-------- 
    ## Browser: QWebKit 
    ## version: 538.1 
    ## --------HAR PAGES-------- 
    ## Page id: 1 , Page title: Poynter – A global leader in journalism. Strengthening democracy. 
    ## --------HAR ENTRIES-------- 
    ## Number of entries: 59 
    ## REQUESTS: 
    ## Page: 1 
    ## Number of entries: 59 
    ##   -  http://www.poynter.org/ 
    ##   -  http://www.poynter.org/wp-content/plugins/easy-author-image/css/easy-author-image.css?ver=2016_06_24.1 
    ##   -  http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css?ver=2016_06_24.1 
    ##   -  http://cloud.webtype.com/css/162ac332-3b31-4b73-ad44-da375b7f2fe3.css?ver=2016_06_24.1 
    ##   -  http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css?ver=2016_06_24.1 
    ##      ........ 
    ##   -  https://tpc.googlesyndication.com/simgad/541736962153447056 
    ##   -  https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjsvXKNpaua7TZAJ3NgGbSrNSD_FL5v3JWJYqTJrtFlSfohBXAFaIfesVO... 
    ##   -  https://s1.2mdn.net/4633855/GSCS-Bnr-Static-FY17-JO-728x90.jpg 
    ##   -  https://tpc.googlesyndication.com/simgad/7969443281248518986 
    ##   -  https://securepubads.g.doubleclick.net/pcs/view?xai=AKAOjssccfdP8TMMHcH0e-osjUw2ZbvdFzIa6ou_YFFD696CmCg6hcG692yUo...

**Comment by hrbrmstr** [comment]
Also added support in `render_json()`

**Comment by johndharrison** [comment]
That worked well thanks Bob!!
