### ISSUE TITLE
can't install splash from R command install_splash()

### ISSUE THREAD

**Issue by guochunshen** [hrbrmstr/splashr#5]
can't install splash from R command install_splash(), even i followed the solution in #3 

> library(splashr)
> install_splash()
Error in sys::exec_internal(docker, args = args, error = TRUE) : 
  Executing '/usr/bin/docker' failed with status 1

my OS is CentOS 7, here is the error message in the log file

Mar 10 11:41:09 localhost systemd: Started Docker Application Container Engine.
Mar 10 11:41:36 localhost chronyd[610]: Source 61.216.153.104 replaced with 202.112.29.82
Mar 10 11:41:54 localhost dockerd-current: time="2017-03-10T11:41:54.777093856+08:00" level=info msg="{Action=create, Username=gcshen, LoginUID=1000, PID=2624}"
Mar 10 11:41:54 localhost dockerd-current: time="2017-03-10T11:41:54.997717009+08:00" level=warning msg="Error getting v2 registry: Get https://registry-1.docker.io/v2/: write tcp 192.168.1.101:49126->50.17.62.194:443: write: connection reset by peer"
Mar 10 11:41:54 localhost dockerd-current: time="2017-03-10T11:41:54.997741287+08:00" level=error msg="Attempting next endpoint for pull after error: Get https://registry-1.docker.io/v2/: write tcp 192.168.1.101:49126->50.17.62.194:443: write: connection reset by peer"
Mar 10 11:41:57 localhost dockerd-current: time="2017-03-10T11:41:57.169904010+08:00" level=error msg="Not continuing with pull after error: Tag latest not found in repository docker.io/hrbrmstr/splashttpd"
Mar 10 11:46:05 localhost dockerd-current: time="2017-03-10T11:46:05.385662113+08:00" level=info msg="{Action=create, Username=gcshen, LoginUID=1000, PID=2644}"
Mar 10 11:46:07 localhost dockerd-current: time="2017-03-10T11:46:07.079760539+08:00" level=error msg="Error trying v2 registry: Get https://registry-1.docker.io/v2/hrbrmstr/splashttpd/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Ahrbrmstr%2Fsplashttpd%3Apull&service=registry.docker.io: read tcp 192.168.1.101:49134->50.17.62.194:443: read: connection reset by peer"
Mar 10 11:46:07 localhost dockerd-current: time="2017-03-10T11:46:07.079797105+08:00" level=error msg="Attempting next endpoint for pull after error: Get https://registry-1.docker.io/v2/hrbrmstr/splashttpd/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Ahrbrmstr%2Fsplashttpd%3Apull&service=registry.docker.io: read tcp 192.168.1.101:49134->50.17.62.194:443: read: connection reset by peer"

**Comment by RobertMyles** [comment]
Can I ask why this was closed? I'm having the same problem :-/

**Comment by hrbrmstr** [comment]
then you have a Docker config issue on your end. I suspect the poster realized that as well and fixed whatever was causing the "connection reset by peer" error message which has absolutely nothing to do with this package or the `harbor` package it uses for Docker ops.

**Comment by RobertMyles** [comment]
Ok, thanks.
