### ISSUE TITLE
how to set headers

### ISSUE THREAD

**Issue by mwhitaker** [hrbrmstr/splashr#8]
In `render-png(...,header,...)` I'd like to be able to set the **user-agent** in the header as some sites look for that to display a mobile version or not. What's the format to use in the headers parameter?

I tried `headers = httr::add_headers(`\`User-Agent\` ` = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.39 Safari/537.36")` and also `list()`,but no luck. If you could point me in the right direction I'd appreciate it.

Thanks for a great package!

**Comment by hrbrmstr** [comment]
Thx for both checking out the package and taking time to file an issue!

You get more granular control with the DSL:

```r
splash_local %>%
  splash_user_agent(ua_macos_chrome) %>%
  splash_go("https://rud.is/b") %>%
  splash_wait(2) %>%
  splash_png()
```
You can set user-agent and even drop into the lua scripting layer that way. The snippet above shld likely work but def let me know if not.

**Comment by mwhitaker** [comment]
Thanks so much, Bob. Must have also missed your detailed Helper Functions and Data vignette that literally talks about impersonating other browsers! I am running across all kinds of instances where I need to know the rendered HTML vs the source.
